name: "tagged-release"

on:
  push:
    tags:
      - "*"


jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "release du projet"
          files: |
            *.jar
