name: "pre-release"

on:
  push:
    branches:
      - main
      - feature*
      - fix*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "release du projet"
          files: |
            *.jar
